---
title: "simple_models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(tidyverse)
library(lubridate)

# Project File Paths

e_actual_rds <- here::here("data/building_energy_actual.rds")
e_sim_rds <- here::here("data/building_energy_sim.rds")

e_actual_csv <- here::here("data/building_energy_actual.csv")
e_actual_stationary_csv <- here::here("data/building_energy_actual_stationary.csv")
e_sim_csv <- here::here("data/building_energy_sim.csv")

e_featurized_rds <- here::here("data/building_energy_featurized.rds")
e_featurized_csv <- here::here("data/building_energy_featurized.csv")

e_featurized_zscore_csv <- here::here("data/building_energy_featurized_zscore.csv")
e_featurized_undo_zscore_csv <- here::here("data/building_energy_featurized_undo_zscore.csv")

e_lstm_zscore_csv <- here::here("data/building_energy_lstm_zscore.csv")
e_lstm_undo_zscore_csv <- here::here("data/building_energy_lstm_undo_zscore.csv")

removed_buildings <- c("00603700220000", "00600360310000", "00600360380000")

set.seed(5)

```

```{r}
e_actual <- read_rds(e_actual_rds)
e_sim <- read_rds(e_sim_rds)
```

Threshold at 1500 for observed.

```{r}
e_actual <- 
  e_actual %>% 
  select(apn, year, month, day, hour, kwh) %>% 
  filter(!(apn %in% removed_buildings) & kwh < 1500) %>% 
  mutate(
    datetime = make_datetime(year, month, day, hour),
    day_of_week = wday(datetime)
  ) %>% 
  select(apn, year, month, day, hour, day_of_week, everything(), -datetime)

e_actual

e_sim <- 
  e_sim %>% 
  select(apn, year, month, day, hour, kwh)

e_actual %>% 
  write_csv(e_actual_csv)

e_sim %>% 
  write_csv(e_sim_csv)
```

```{r}
e_actual %>% 
  group_by(apn, year) %>% 
  arrange(year) %>% 
  mutate(mean_first_year = mean(kwh)) %>% 
  group_by(apn) %>% 
  mutate(
    mean_first_year = mean_first_year %>% head(1)
  ) %>% 
  group_by(apn, year) %>% 
  mutate(kwh = kwh * mean_first_year / mean(kwh)) %>% 
  filter(apn == "00600340190000") %>%
  mutate(datetime = make_datetime(year, month, day, hour)) %>% 
  ggplot(aes(datetime, kwh)) +
  geom_line()

e_actual %>% 
  group_by(apn, year) %>% 
  arrange(year) %>% 
  mutate(mean_first_year = mean(kwh)) %>% 
  group_by(apn) %>% 
  mutate(
    mean_first_year = mean_first_year %>% head(1)
  ) %>% 
  group_by(apn, year) %>% 
  mutate(kwh = kwh * mean_first_year / mean(kwh)) %>% 
  select(-mean_first_year) %>% 
  write_csv(e_actual_stationary_csv)
```

`one_hot` function: [link](https://gist.github.com/EmilHvitfeldt/482412fa4ea7246a11c7b7a8504b7997)

```{r}
one_hot <- function(data, var) {
  items <- data %>% pull({{var}})
  items_unique <- items %>% unique()
  
  out <- matrix(0, nrow(data), length(items_unique))
  colnames(out) <- items_unique
  
  for (i in items_unique) {
    out[, i] <- items == i
  }
  out
  data %>%
    select(-{{var}}) %>%
    bind_cols(
      as_tibble(out) %>% 
        rename_all(~ str_c("target_", .)) %>%
        mutate_all(as.integer)
    )
}
```

```{r}
e_featurized <- 
  e_actual %>%
  arrange(apn) %>% 
  rename(kwh_actual = kwh) %>% 
  one_hot(apn) %>% 
  left_join(
    e_sim %>% 
      pivot_wider(
        names_from = apn,
        names_prefix = "kwh_sim_",
        values_from = kwh
      )
  )
```

```{r}
e_featurized %>% 
  write_rds(e_featurized_rds)

e_featurized %>% 
  write_csv(e_featurized_csv)
```

```{r}
# z-score of each building for both kwh_actual and kwh_sim
e_featurized_zscore <- 
  e_sim %>% 
  select(-kwh) %>% 
  left_join(e_actual) %>% 
  drop_na() %>% 
  group_by(apn) %>% 
  mutate(
    mean_kwh = mean(kwh),
    sd_kwh = sd(kwh),
    kwh = scale(kwh)
  ) %>% 
  ungroup() %>% 
  rename(kwh_actual = kwh) %>%
  one_hot(apn) %>%
  left_join(
    e_sim %>%
      pivot_wider(
        names_from = apn,
        names_prefix = "kwh_sim_",
        values_from = kwh
      ) %>% 
      mutate_at(vars(starts_with("kwh_sim_")), ~ scale(.) %>% as.vector)
  )
    
e_featurized_undo_zscore <- 
  e_sim %>% 
  select(-kwh) %>% 
  left_join(e_actual) %>% 
  drop_na() %>% 
  group_by(apn) %>% 
  summarize(
    mean_kwh = mean(kwh),
    sd_kwh = sd(kwh)
  )
```

```{r}
e_featurized_zscore %>% 
  write_csv(e_featurized_zscore_csv)

e_featurized_undo_zscore %>% 
  write_csv(e_featurized_undo_zscore_csv)
```

```{r}
e_featurized_zscore %>% 
  filter(year == 2019)
```


```{r}
e_sim %>% 
  pivot_wider(
    names_from = apn,
    names_prefix = "kwh_actual_",
    values_from = kwh
  ) %>% 
  mutate(
    date_time = make_datetime(year, month, day, hour),
  ) %>%
  select(date_time, everything()) %>% 
  drop_na() %>% 
  mutate(
    diff = date_time - lag(date_time)
  ) %>% 
  select(diff, everything()) %>% 
  count(diff)

e_actual %>% 
  pivot_wider(
    names_from = apn,
    names_prefix = "kwh_actual_",
    values_from = kwh
  ) %>% 
  mutate(
    date_time = make_datetime(year, month, day, hour)
  ) %>% 
  select(date_time, everything()) %>% 
  drop_na() %>% 
  mutate(
    diff = date_time - lag(date_time)
  ) %>% 
  select(diff, everything()) %>% 
  count(diff)
```

```{r}
e_lstm_original <- 
  e_sim %>% 
  filter(apn %in% (e_actual %>% pull(apn) %>% unique())) %>% 
  rename(kwh_sim = kwh) %>% 
  left_join(e_actual) %>% 
  rename(kwh_actual = kwh) %>% 
  pivot_wider(
    names_from = apn,
    values_from = c("kwh_actual", "kwh_sim")
  ) %>% 
  mutate_all(
    ~ if_else(
      is.na(.), 
      mean(., na.rm = TRUE) %>% as.integer(), 
      as.integer(.)
    )
  )

e_lstm_zscore <- 
  e_lstm_original %>% 
  mutate(year = if_else(year == 2019L, 2016L, year)) %>% 
  arrange(year, month, day, hour) %>% 
  filter(!(month == 2 & day == 29)) %>% 
  mutate_at(vars(starts_with("kwh_")), ~ scale(.) %>% as.vector) %>%
  select(year, month, day, hour, starts_with("kwh_sim"), everything())
  
e_lstm_undo_zscore <- 
  e_lstm_original %>% 
  select(-starts_with("kwh_sim")) %>% 
  pivot_longer(
    cols = starts_with("kwh_actual_"),
    names_to = "apn",
    names_prefix = "kwh_actual_",
    values_to = "kwh"
  ) %>%
  group_by(apn) %>% 
  summarize(
    mean_kwh = mean(kwh),
    sd_kwh = sd(kwh)
  )

```

```{r}
e_lstm_original %>% 
  filter(year == 2018)
```


```{r}
e_lstm_zscore %>% 
  write_csv(e_lstm_zscore_csv)

e_lstm_undo_zscore %>% 
  write_csv(e_lstm_undo_zscore_csv)
```

END OF DATA WRANGLING CODE

```{r}
e_sim %>% 
  rename(kwh_sim = kwh) %>% 
  left_join(e_actual) %>% 
  drop_na(kwh) %>% 
  mutate(diff = kwh - kwh_sim) %>% 
  ggplot(aes(diff)) +
  geom_vline(aes(xintercept = mean(diff, na.rm = TRUE)), color = "red") +
  geom_vline(aes(xintercept = median(diff, na.rm = TRUE)), color = "blue") +
  geom_histogram(binwidth = 20) +
  labs(
    title = "Distribution of difference in energy use (observed - simulated)",
    subtitle = "Median in blue, mean in red. Most observations close to simulations",
    x = "Observed - Simulated (kwh)",
    y = "Frequency",
    caption = "Source: Sacramento Municipal Utility District"
  )
```

```{r}
e_sim %>% 
  rename(kwh_sim = kwh) %>% 
  left_join(e_actual) %>% 
  drop_na(kwh) %>% 
  mutate(kwh = kwh - kwh_sim) %>% 
  mutate(month = lubridate::month(month, label = TRUE)) %>%
  group_by(month, hour, apn) %>% 
  summarize(mean_kwh_building = mean(kwh, na.rm = TRUE)) %>% 
  summarize(mean_kwh = mean(mean_kwh_building, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(hour, fct_rev(month), fill = mean_kwh)) +
  geom_tile() +
  scale_x_continuous(expand = expand_scale()) +
  scale_y_discrete(expand = expand_scale()) +
  scale_fill_distiller(palette = "RdYlBu") +
  labs(
    title = "Mean difference between observed and simulated energy usage per month",
    subtitle = "Observations too low midday in winter and too high morning/evening in summer",
    x = "Hour",
    y = "Month",
    fill = "Obs - Sim \n(kWh)",
    caption = "Source: Sacramento Municipal Utility District"
  )
```

```{r}
test <- 
  e_featurized %>% 
  # filter(target_00600340190000 == 1) %>% 
  select_at(vars(-starts_with("target_"))) %>% 
  mutate_all(~ scale(.) %>% as.vector)

linearMod <- lm(kwh_actual ~ ., data = test)

linearMod %>% summary()
```

